name: ci
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: 
      id-token: write
      contents: write
      pull-requests: write
  
    steps:
      - run: cat $GITHUB_EVENT_PATH

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install
